org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
android.ndkPath=/Users/akshatpratap/HealthOK/.tooling/android-ndk-r28c
android.suppressNdkDownload=true
flutter.sdkManagerPath=/Users/akshatpratap/HealthOK/.tooling/dummy-sdkmanager/sdkmanager
flutter.installedNdkVersions=28.2.13676358
android.ndkVersion=28.2.13676358
flutter.compileSdkVersion=36
systemProp.ANDROID_HOME=/Users/akshatpratap/HealthOK/.tooling/android-sdk
systemProp.ANDROID_SDK_ROOT=/Users/akshatpratap/HealthOK/.tooling/android-sdk
