import 'package:flutter/material.dart';
import 'package:health/health.dart' as health;
import 'package:health_ok/main.dart' show AppColors;
import 'package:health_ok/src/services/quest_service.dart';
import 'package:health_ok/src/services/hydration_service.dart';
import 'package:health_ok/src/services/workout_service.dart';
import 'package:health_ok/src/services/achievement_service.dart';
import 'package:health_ok/src/theme/app_colors.dart';
import 'package:share_plus/share_plus.dart';
import 'package:quest_engine/quest_engine.dart';

/// Generates and shares a weekly health report.
class WeeklyReportScreen extends StatefulWidget {
  const WeeklyReportScreen({super.key});

  @override
  State<WeeklyReportScreen> createState() => _WeeklyReportScreenState();
}

class _WeeklyReportScreenState extends State<WeeklyReportScreen> {
  String _report = '';
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _generate();
  }

  Future<void> _generate() async {
    setState(() => _loading = true);
    try {
      final h = health.Health();
      final now = DateTime.now();
      final weekAgo = now.subtract(const Duration(days: 7));
      final player = await QuestService.loadPlayer();
      final workouts = await WorkoutService.getLast7Days();
      final unlockedIds = await AchievementService.getUnlocked();
      final unlockedAchs = AchievementService.all.where((a) => unlockedIds.contains(a.id)).toList();

      final data = await h.getHealthDataFromTypes(
        types: [
          health.HealthDataType.STEPS,
          health.HealthDataType.DISTANCE_DELTA,
          health.HealthDataType.ACTIVE_ENERGY_BURNED,
        ],
        startTime: weekAgo,
        endTime: now,
      );

      double totalSteps = 0, totalDist = 0, totalCal = 0;
      for (final s in data) {
        if (s.value is! health.NumericHealthValue) continue;
        final v = (s.value as health.NumericHealthValue).numericValue.toDouble();
        if (s.type == health.HealthDataType.STEPS) totalSteps += v;
        if (s.type == health.HealthDataType.DISTANCE_DELTA) totalDist += v;
        if (s.type == health.HealthDataType.ACTIVE_ENERGY_BURNED) totalCal += v;
      }

      final hydration = await HydrationService.getLast7Days();
      final avgHydration = hydration.isNotEmpty
          ? hydration.reduce((a, b) => a + b) / hydration.length
          : 0.0;

      final StringBuffer sb = StringBuffer();
      sb.writeln('═══════════════════════════════════');
      sb.writeln('  ⚔️  HEALTHOK WEEKLY REPORT');
      sb.writeln('  ${_formatDate(weekAgo)} — ${_formatDate(now)}');
      sb.writeln('═══════════════════════════════════');
      sb.writeln();
      sb.writeln('👤 HUNTER PROFILE');
      sb.writeln('  Level: ${player.level} | Rank: ${player.rank.name.toUpperCase()}');
      sb.writeln('  XP: ${player.xp} | Streak: ${player.streakDays} days');
      sb.writeln('  STR: ${player.strength} | AGI: ${player.agility} | VIT: ${player.vitality}');
      sb.writeln('  INT: ${player.intelligence} | PER: ${player.perception}');
      sb.writeln();
      sb.writeln('📊 ACTIVITY SUMMARY');
      sb.writeln('  Steps:     ${totalSteps.toStringAsFixed(0)}');
      sb.writeln('  Distance:  ${totalDist.toStringAsFixed(2)} km');
      sb.writeln('  Calories:  ${totalCal.toStringAsFixed(0)} kcal');
      sb.writeln('  Workouts:  ${workouts.length}');
      sb.writeln('  Hydration: ${avgHydration.toStringAsFixed(0)} mL avg/day');
      sb.writeln();
      if (workouts.isNotEmpty) {
        sb.writeln('💪 WORKOUTS');
        for (final w in workouts) {
          sb.writeln('  ${w.type.emoji} ${w.type.label} — ${w.durationMinutes}m, ${w.caloriesBurned} kcal (+${w.xpEarned} XP)');
        }
        sb.writeln();
      }
      sb.writeln('🏆 ACHIEVEMENTS');
      sb.writeln('  ${unlockedIds.length}/${AchievementService.all.length} unlocked');
      for (final a in unlockedAchs) {
        sb.writeln('  ${a.icon} ${a.title}');
      }
      sb.writeln();
      sb.writeln('═══════════════════════════════════');
      sb.writeln('  Generated by HealthOK • ${DateTime.now().toString().substring(0, 10)}');
      sb.writeln('═══════════════════════════════════');

      if (!mounted) return;
      setState(() {
        _report = sb.toString();
        _loading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _report = 'Error generating report: $e';
        _loading = false;
      });
    }
  }

  String _formatDate(DateTime d) =>
      '${d.month.toString().padLeft(2, '0')}/${d.day.toString().padLeft(2, '0')}/${d.year}';

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration:  BoxDecoration(gradient: AppColors.bgGradient),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          leading: IconButton(
            icon:  Icon(Icons.arrow_back_rounded, color: AppColors.textPrimary),
            onPressed: () => Navigator.pop(context),
          ),
          title:  Text(
            'Weekly Report',
            style: TextStyle(color: AppColors.textPrimary, fontWeight: FontWeight.w700),
          ),
          actions: [
            if (!_loading)
              IconButton(
                icon: const Icon(Icons.share_rounded, color: AppColors.primary),
                onPressed: () => Share.share(_report, subject: 'HealthOK Weekly Report'),
              ),
          ],
        ),
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: _loading
                ?  Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        CircularProgressIndicator(color: AppColors.primary),
                        SizedBox(height: 16),
                        Text('Generating your weekly report...',
                            style: TextStyle(color: AppColors.textMuted)),
                      ],
                    ),
                  )
                : Column(
                    children: [
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          gradient: const LinearGradient(
                            colors: [Color(0xFF6366F1), Color(0xFF8B5CF6)],
                          ),
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: const Row(
                          children: [
                            Text('📄', style: TextStyle(fontSize: 32)),
                            SizedBox(width: 14),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text('Your Weekly Report',
                                      style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 18,
                                          fontWeight: FontWeight.w800)),
                                  Text('Tap share to save or send',
                                      style: TextStyle(color: Colors.white70, fontSize: 12)),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 16),
                      Expanded(
                        child: Container(
                          width: double.infinity,
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: AppColors.surface,
                            borderRadius: BorderRadius.circular(16),
                            border: Border.all(color: AppColors.lightBorder),
                          ),
                          child: SingleChildScrollView(
                            child: Text(
                              _report,
                              style:  TextStyle(
                                  fontSize: 12,
                                  fontFamily: 'monospace',
                                  color: AppColors.textPrimary,
                                  height: 1.5),
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 16),
                      SizedBox(
                        width: double.infinity,
                        height: 48,
                        child: ElevatedButton.icon(
                          onPressed: () => Share.share(_report, subject: 'HealthOK Weekly Report'),
                          icon: const Icon(Icons.share_rounded, color: Colors.white),
                          label: const Text(
                            'Share Report',
                            style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.w800),
                          ),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.primary,
                            elevation: 0,
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(16)),
                          ),
                        ),
                      ),
                    ],
                  ),
          ),
        ),
      ),
    );
  }
}